apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-helm-repo
  namespace: flux-system-local
spec:
  interval: 5m
  chart:
    spec:
      chart: ./tests/test-local
      sourceRef:
        kind: GitRepository
        name: local-chart
        namespace: flux-system
      interval: 600m
  values:
    replicaCount: 10
